# Generated by Django 2.2.6 on 2022-04-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipleimages', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
