# Generated by Django 2.2.6 on 2022-04-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ImageModel',
        ),
    ]
